export enum FakerActionTypes {
  RETRIEVE_NAME_DETAILS = "RETRIEVE_NAME_DETAILS",
  RETRIEVE_PHONE_DETAILS = "RETRIEVE_RETRIEVE_PHONE_DETAILS_DETAILS",
  RETRIEVE_RANDOM_DETAILS = "RETRIEVE_RANDOM_DETAILS"
}